# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
