# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_auto_20170315_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='blog_list',
        ),
        migrations.AddField(
            model_name='webpage',
            name='blog_list',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='blogsite.Blog'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='n_comments',
        ),
        migrations.AddField(
            model_name='webpage',
            name='n_comments',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='blogsite.Comment'),
            preserve_default=False,
        ),
    ]
