# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_auto_20170316_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='n_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogsite.Comment'),
        ),
    ]
