# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_auto_20170316_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='webpages',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='blog_list',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='n_comments',
        ),
        migrations.AddField(
            model_name='blog',
            name='web_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_list', to='blogsite.WebPage'),
        ),
        migrations.AddField(
            model_name='comment',
            name='web_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='n_comments', to='blogsite.WebPage'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='mainpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webpages', to='blogsite.MainPage'),
        ),
    ]
