# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0006_auto_20170317_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='log_date',
            field=models.DateField(auto_now=True),
        ),
    ]
